### ISSUE TITLE
ClassNotFoundException when adding captcha to FormBuilder

### ISSUE THREAD

**Issue by plaberinto** [DarioSwain/DSReCaptchaBundle#2]
Hello.

I get a ClassNotFoundException when adding ->add('captcha', 'ds_re_captcha', array('mapped' => false)) inside the buildForm method. The complete message is: 

Attempted to load class "ReCaptchaType" from namespace "DS\Component\ReCaptcha\Form".
Did you forget a "use" statement for another namespace?

Can you help me? Thanks

**Comment by plaberinto** [comment]
Ok, I found the bug. The Resources/config/services.yml is wrong. Te classes should be:

DS\Component\ReCaptchaValidator\ReCaptchaValidator

and

DS\Component\ReCaptchaValidator\Form\ReCaptchaType

Fixing this, it works

**Comment by plaberinto** [comment]
Sorry, I made a mistake. The correct classes are:

DS\Component\ReCaptchaValidator\Validator\ReCaptchaValidator

and

DS\Component\ReCaptchaValidator\Form\ReCaptchaType

**Comment by IlyaPokamestov** [comment]
@plaberinto I'm sorry, I will not be available until June. I plan to continue working on the bundle after returning.
Can you create PR for this issue?

**Comment by plaberinto** [comment]
Hello.

Well, it's not the only issue en version 2.6 of Symfony. It dosn't work
because of the CSRF protection, trying to get the value of the form field
"g-recaptcha-response", generated by the js of reCaptcha. I'm working on it.

2015-04-19 14:16 GMT+02:00 Ilya Pokamestov notifications@github.com:

**Comment by IlyaPokamestov** [comment]
Hi @plaberinto!
I check this issue and don't found any problems:(
I reproduce all steps on Symfony 2.6.9 and CSRF protection work fine for me.

Can you get more info for this issue?

**Comment by IlyaPokamestov** [comment]
@plaberinto  please reopen this issue if you can reproduce this.
